apiVersion: v1
kind: Namespace
metadata:
  name: technitium-dns
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-dns-pvc
  namespace: technitium-dns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: technitium-dns
  namespace: technitium-dns
  labels:
    app: technitium-dns
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: technitium-dns
  template:
    metadata:
      labels:
        app: technitium-dns
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: dns-server
          image: technitium/dns-server:13.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: web-http
              containerPort: 5380
              protocol: TCP
          env:
            - name: TZ
              value: "UTC"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/dns
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: technitium-dns-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: technitium-dns-service
  namespace: technitium-dns
spec:
  type: NodePort
  selector:
    app: technitium-dns
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      nodePort: 30053
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      nodePort: 30053
      protocol: TCP
    - name: web-http
      port: 5380
      targetPort: 5380
      nodePort: 30378
      protocol: TCP
